// <auto-generated />
using System;
using Ideastudio.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ideastudio.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20200618164025_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ideastudio.Domain.GlavniProjektant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("BrojLicence")
                        .HasColumnType("bigint");

                    b.Property<string>("ImePrezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Zvanje")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("GlavniProjektant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrojLicence = 134L,
                            ImePrezime = "ImePrezime 1",
                            Zvanje = "Zvanje 1"
                        },
                        new
                        {
                            Id = 2,
                            BrojLicence = 54L,
                            ImePrezime = "ImePrezime 2",
                            Zvanje = "Zvanje 2"
                        },
                        new
                        {
                            Id = 3,
                            BrojLicence = 5343L,
                            ImePrezime = "ImePrezime 3",
                            Zvanje = "Zvanje 3"
                        },
                        new
                        {
                            Id = 4,
                            BrojLicence = 28L,
                            ImePrezime = "ImePrezime 4",
                            Zvanje = "Zvanje 4"
                        },
                        new
                        {
                            Id = 5,
                            BrojLicence = 335L,
                            ImePrezime = "ImePrezime 5",
                            Zvanje = "Zvanje 5"
                        });
                });

            modelBuilder.Entity("Ideastudio.Domain.IdejnoResenje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumIzrade")
                        .HasColumnType("datetime2");

                    b.Property<int>("GlavniProjektantId")
                        .HasColumnType("int");

                    b.Property<int>("LokacijskaDozvolaId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("ObjekatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GlavniProjektantId");

                    b.HasIndex("LokacijskaDozvolaId");

                    b.HasIndex("ObjekatId");

                    b.ToTable("IdejnoResenje");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DatumIzrade = new DateTime(2020, 6, 18, 16, 40, 24, 747, DateTimeKind.Utc).AddTicks(1710),
                            GlavniProjektantId = 2,
                            LokacijskaDozvolaId = 1,
                            Naziv = "Idejno resenje 1",
                            ObjekatId = 4
                        },
                        new
                        {
                            Id = 2,
                            DatumIzrade = new DateTime(2020, 6, 18, 16, 40, 24, 747, DateTimeKind.Utc).AddTicks(3645),
                            GlavniProjektantId = 5,
                            LokacijskaDozvolaId = 5,
                            Naziv = "Idejno resenje 2",
                            ObjekatId = 1
                        },
                        new
                        {
                            Id = 3,
                            DatumIzrade = new DateTime(2020, 6, 18, 16, 40, 24, 747, DateTimeKind.Utc).AddTicks(3680),
                            GlavniProjektantId = 1,
                            LokacijskaDozvolaId = 3,
                            Naziv = "Idejno resenje 3",
                            ObjekatId = 3
                        },
                        new
                        {
                            Id = 4,
                            DatumIzrade = new DateTime(2020, 6, 18, 16, 40, 24, 747, DateTimeKind.Utc).AddTicks(3683),
                            GlavniProjektantId = 4,
                            LokacijskaDozvolaId = 2,
                            Naziv = "Idejno resenje 4",
                            ObjekatId = 2
                        },
                        new
                        {
                            Id = 5,
                            DatumIzrade = new DateTime(2020, 6, 18, 16, 40, 24, 747, DateTimeKind.Utc).AddTicks(3686),
                            GlavniProjektantId = 3,
                            LokacijskaDozvolaId = 4,
                            Naziv = "Idejno resenje 5",
                            ObjekatId = 5
                        },
                        new
                        {
                            Id = 6,
                            DatumIzrade = new DateTime(2020, 6, 18, 16, 40, 24, 747, DateTimeKind.Utc).AddTicks(3688),
                            GlavniProjektantId = 2,
                            LokacijskaDozvolaId = 1,
                            Naziv = "Idejno resenje 6",
                            ObjekatId = 3
                        },
                        new
                        {
                            Id = 7,
                            DatumIzrade = new DateTime(2020, 6, 18, 16, 40, 24, 747, DateTimeKind.Utc).AddTicks(3690),
                            GlavniProjektantId = 1,
                            LokacijskaDozvolaId = 2,
                            Naziv = "Idejno resenje 7",
                            ObjekatId = 3
                        },
                        new
                        {
                            Id = 8,
                            DatumIzrade = new DateTime(2020, 6, 18, 16, 40, 24, 747, DateTimeKind.Utc).AddTicks(3692),
                            GlavniProjektantId = 2,
                            LokacijskaDozvolaId = 4,
                            Naziv = "Idejno resenje 8",
                            ObjekatId = 4
                        },
                        new
                        {
                            Id = 9,
                            DatumIzrade = new DateTime(2020, 6, 18, 16, 40, 24, 747, DateTimeKind.Utc).AddTicks(3694),
                            GlavniProjektantId = 4,
                            LokacijskaDozvolaId = 4,
                            Naziv = "Idejno resenje 9",
                            ObjekatId = 4
                        },
                        new
                        {
                            Id = 10,
                            DatumIzrade = new DateTime(2020, 6, 18, 16, 40, 24, 747, DateTimeKind.Utc).AddTicks(3695),
                            GlavniProjektantId = 4,
                            LokacijskaDozvolaId = 5,
                            Naziv = "Idejno resenje 10",
                            ObjekatId = 5
                        });
                });

            modelBuilder.Entity("Ideastudio.Domain.InformacijeOLokaciji", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumIzdavanja")
                        .HasColumnType("datetime2");

                    b.Property<string>("NamenaZemljista")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("InformacijeOLokaciji");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DatumIzdavanja = new DateTime(2020, 6, 18, 16, 40, 24, 744, DateTimeKind.Utc).AddTicks(9821),
                            NamenaZemljista = "Namena 1",
                            Naziv = "Informacije o lokaciji 1",
                            Zona = "Zona 1"
                        },
                        new
                        {
                            Id = 2,
                            DatumIzdavanja = new DateTime(2020, 6, 18, 16, 40, 24, 745, DateTimeKind.Utc).AddTicks(1449),
                            NamenaZemljista = "Namena 2",
                            Naziv = "Informacije o lokaciji 2",
                            Zona = "Zona 2"
                        },
                        new
                        {
                            Id = 3,
                            DatumIzdavanja = new DateTime(2020, 6, 18, 16, 40, 24, 745, DateTimeKind.Utc).AddTicks(1518),
                            NamenaZemljista = "Namena 3",
                            Naziv = "Informacije o lokaciji 3",
                            Zona = "Zona 3"
                        },
                        new
                        {
                            Id = 4,
                            DatumIzdavanja = new DateTime(2020, 6, 18, 16, 40, 24, 745, DateTimeKind.Utc).AddTicks(1527),
                            NamenaZemljista = "Namena 4",
                            Naziv = "Informacije o lokaciji 4",
                            Zona = "Zona 4"
                        },
                        new
                        {
                            Id = 5,
                            DatumIzdavanja = new DateTime(2020, 6, 18, 16, 40, 24, 745, DateTimeKind.Utc).AddTicks(1530),
                            NamenaZemljista = "Namena 5",
                            Naziv = "Informacije o lokaciji 5",
                            Zona = "Zona 5"
                        },
                        new
                        {
                            Id = 6,
                            DatumIzdavanja = new DateTime(2020, 6, 18, 16, 40, 24, 745, DateTimeKind.Utc).AddTicks(1533),
                            NamenaZemljista = "Namena 6",
                            Naziv = "Informacije o lokaciji 6",
                            Zona = "Zona 6"
                        },
                        new
                        {
                            Id = 7,
                            DatumIzdavanja = new DateTime(2020, 6, 18, 16, 40, 24, 745, DateTimeKind.Utc).AddTicks(1536),
                            NamenaZemljista = "Namena 7",
                            Naziv = "Informacije o lokaciji 7",
                            Zona = "Zona 7"
                        },
                        new
                        {
                            Id = 8,
                            DatumIzdavanja = new DateTime(2020, 6, 18, 16, 40, 24, 745, DateTimeKind.Utc).AddTicks(1538),
                            NamenaZemljista = "Namena 8",
                            Naziv = "Informacije o lokaciji 8",
                            Zona = "Zona 8"
                        },
                        new
                        {
                            Id = 9,
                            DatumIzdavanja = new DateTime(2020, 6, 18, 16, 40, 24, 745, DateTimeKind.Utc).AddTicks(1541),
                            NamenaZemljista = "Namena 9",
                            Naziv = "Informacije o lokaciji 9",
                            Zona = "Zona 9"
                        },
                        new
                        {
                            Id = 10,
                            DatumIzdavanja = new DateTime(2020, 6, 18, 16, 40, 24, 745, DateTimeKind.Utc).AddTicks(1544),
                            NamenaZemljista = "Namena 10",
                            Naziv = "Informacije o lokaciji 10",
                            Zona = "Zona 10"
                        });
                });

            modelBuilder.Entity("Ideastudio.Domain.LokacijskaDozvola", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("BrojParcele")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DatumIzdavanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("InformacijeOLokacijiId")
                        .HasColumnType("int");

                    b.Property<string>("LokacijskiUslovi")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NazivIdejnogResenja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpstiPodaci")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<long>("PovrsinaParcele")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InformacijeOLokacijiId");

                    b.ToTable("LokacijskaDozvola");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrojParcele = 6934L,
                            DatumIzdavanja = new DateTime(2020, 6, 18, 16, 40, 24, 746, DateTimeKind.Utc).AddTicks(7829),
                            InformacijeOLokacijiId = 3,
                            LokacijskiUslovi = "Lokacijski uslovi 1",
                            Naziv = "Lokacijska dozvola 1",
                            OpstiPodaci = "Opsti podaci 1",
                            PovrsinaParcele = 324L
                        },
                        new
                        {
                            Id = 2,
                            BrojParcele = 48643L,
                            DatumIzdavanja = new DateTime(2020, 6, 18, 16, 40, 24, 746, DateTimeKind.Utc).AddTicks(8980),
                            InformacijeOLokacijiId = 2,
                            LokacijskiUslovi = "Lokacijski uslovi 2",
                            Naziv = "Lokacijska dozvola 2",
                            OpstiPodaci = "Opsti podaci 2",
                            PovrsinaParcele = 412L
                        },
                        new
                        {
                            Id = 3,
                            BrojParcele = 4843L,
                            DatumIzdavanja = new DateTime(2020, 6, 18, 16, 40, 24, 746, DateTimeKind.Utc).AddTicks(8998),
                            InformacijeOLokacijiId = 5,
                            LokacijskiUslovi = "Lokacijski uslovi 3",
                            Naziv = "Lokacijska dozvola 3",
                            OpstiPodaci = "Opsti podaci 3",
                            PovrsinaParcele = 3453L
                        },
                        new
                        {
                            Id = 4,
                            BrojParcele = 3458L,
                            DatumIzdavanja = new DateTime(2020, 6, 18, 16, 40, 24, 746, DateTimeKind.Utc).AddTicks(9002),
                            InformacijeOLokacijiId = 1,
                            LokacijskiUslovi = "Lokacijski uslovi 4",
                            Naziv = "Lokacijska dozvola 4",
                            OpstiPodaci = "Opsti podaci 4",
                            PovrsinaParcele = 34534L
                        },
                        new
                        {
                            Id = 5,
                            BrojParcele = 34343L,
                            DatumIzdavanja = new DateTime(2020, 6, 18, 16, 40, 24, 746, DateTimeKind.Utc).AddTicks(9004),
                            InformacijeOLokacijiId = 4,
                            LokacijskiUslovi = "Lokacijski uslovi 5",
                            Naziv = "Lokacijska dozvola 5",
                            OpstiPodaci = "Opsti podaci 5",
                            PovrsinaParcele = 3483L
                        });
                });

            modelBuilder.Entity("Ideastudio.Domain.Objekat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Dimenzije")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Karakteristike")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Objekat");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dimenzije = 323m,
                            Karakteristike = "Karakteristika 1",
                            Naziv = "Objekat 1"
                        },
                        new
                        {
                            Id = 2,
                            Dimenzije = 432m,
                            Karakteristike = "Karakteristika 2",
                            Naziv = "Objekat 2"
                        },
                        new
                        {
                            Id = 3,
                            Dimenzije = 545m,
                            Karakteristike = "Karakteristika 3",
                            Naziv = "Objekat 3"
                        },
                        new
                        {
                            Id = 4,
                            Dimenzije = 216m,
                            Karakteristike = "Karakteristika 4",
                            Naziv = "Objekat 4"
                        },
                        new
                        {
                            Id = 5,
                            Dimenzije = 786m,
                            Karakteristike = "Karakteristika 5",
                            Naziv = "Objekat 5"
                        });
                });

            modelBuilder.Entity("Ideastudio.Domain.Povrsina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Oznaka")
                        .HasColumnType("int");

                    b.Property<int>("ProjekatZaGradjevinskuDozvoluId")
                        .HasColumnType("int");

                    b.Property<string>("ProstorijaNaziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VrstaPoda")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("VrstaPovrsineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjekatZaGradjevinskuDozvoluId");

                    b.HasIndex("VrstaPovrsineId");

                    b.ToTable("Povrsina");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Povrsina 1",
                            Oznaka = 1423,
                            ProjekatZaGradjevinskuDozvoluId = 1,
                            Status = 0,
                            VrstaPoda = "Vrsta 1",
                            VrstaPovrsineId = 4
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "Povrsina 2",
                            Oznaka = 755,
                            ProjekatZaGradjevinskuDozvoluId = 4,
                            Status = 0,
                            VrstaPoda = "Vrsta 2",
                            VrstaPovrsineId = 2
                        },
                        new
                        {
                            Id = 3,
                            Naziv = "Povrsina 3",
                            Oznaka = 678,
                            ProjekatZaGradjevinskuDozvoluId = 3,
                            Status = 0,
                            VrstaPoda = "Vrsta 3",
                            VrstaPovrsineId = 3
                        },
                        new
                        {
                            Id = 4,
                            Naziv = "Povrsina 4",
                            Oznaka = 7434,
                            ProjekatZaGradjevinskuDozvoluId = 5,
                            Status = 0,
                            VrstaPoda = "Vrsta 4",
                            VrstaPovrsineId = 1
                        },
                        new
                        {
                            Id = 5,
                            Naziv = "Povrsina 5",
                            Oznaka = 231,
                            ProjekatZaGradjevinskuDozvoluId = 3,
                            Status = 0,
                            VrstaPoda = "Vrsta 5",
                            VrstaPovrsineId = 5
                        },
                        new
                        {
                            Id = 6,
                            Naziv = "Povrsina 6",
                            Oznaka = 3121,
                            ProjekatZaGradjevinskuDozvoluId = 3,
                            Status = 0,
                            VrstaPoda = "Vrsta 6",
                            VrstaPovrsineId = 5
                        },
                        new
                        {
                            Id = 7,
                            Naziv = "Povrsina 7",
                            Oznaka = 542,
                            ProjekatZaGradjevinskuDozvoluId = 2,
                            Status = 0,
                            VrstaPoda = "Vrsta 7",
                            VrstaPovrsineId = 1
                        },
                        new
                        {
                            Id = 8,
                            Naziv = "Povrsina 8",
                            Oznaka = 64,
                            ProjekatZaGradjevinskuDozvoluId = 2,
                            Status = 0,
                            VrstaPoda = "Vrsta 8",
                            VrstaPovrsineId = 1
                        },
                        new
                        {
                            Id = 9,
                            Naziv = "Povrsina 9",
                            Oznaka = 113,
                            ProjekatZaGradjevinskuDozvoluId = 1,
                            Status = 0,
                            VrstaPoda = "Vrsta 9",
                            VrstaPovrsineId = 2
                        },
                        new
                        {
                            Id = 10,
                            Naziv = "Povrsina 10",
                            Oznaka = 11,
                            ProjekatZaGradjevinskuDozvoluId = 1,
                            Status = 0,
                            VrstaPoda = "Vrsta 10",
                            VrstaPovrsineId = 3
                        },
                        new
                        {
                            Id = 11,
                            Naziv = "Povrsina 11",
                            Oznaka = 432,
                            ProjekatZaGradjevinskuDozvoluId = 1,
                            Status = 0,
                            VrstaPoda = "Vrsta 11",
                            VrstaPovrsineId = 4
                        },
                        new
                        {
                            Id = 12,
                            Naziv = "Povrsina 12",
                            Oznaka = 554,
                            ProjekatZaGradjevinskuDozvoluId = 4,
                            Status = 0,
                            VrstaPoda = "Vrsta 12",
                            VrstaPovrsineId = 2
                        },
                        new
                        {
                            Id = 13,
                            Naziv = "Povrsina 13",
                            Oznaka = 32,
                            ProjekatZaGradjevinskuDozvoluId = 3,
                            Status = 0,
                            VrstaPoda = "Vrsta 13",
                            VrstaPovrsineId = 3
                        },
                        new
                        {
                            Id = 14,
                            Naziv = "Povrsina 14",
                            Oznaka = 456,
                            ProjekatZaGradjevinskuDozvoluId = 5,
                            Status = 0,
                            VrstaPoda = "Vrsta 14",
                            VrstaPovrsineId = 1
                        },
                        new
                        {
                            Id = 15,
                            Naziv = "Povrsina 15",
                            Oznaka = 231,
                            ProjekatZaGradjevinskuDozvoluId = 3,
                            Status = 0,
                            VrstaPoda = "Vrsta 15",
                            VrstaPovrsineId = 5
                        },
                        new
                        {
                            Id = 16,
                            Naziv = "Povrsina 16",
                            Oznaka = 411,
                            ProjekatZaGradjevinskuDozvoluId = 3,
                            Status = 0,
                            VrstaPoda = "Vrsta 16",
                            VrstaPovrsineId = 5
                        },
                        new
                        {
                            Id = 17,
                            Naziv = "Povrsina 17",
                            Oznaka = 231,
                            ProjekatZaGradjevinskuDozvoluId = 2,
                            Status = 0,
                            VrstaPoda = "Vrsta 17",
                            VrstaPovrsineId = 1
                        },
                        new
                        {
                            Id = 18,
                            Naziv = "Povrsina 18",
                            Oznaka = 467,
                            ProjekatZaGradjevinskuDozvoluId = 2,
                            Status = 0,
                            VrstaPoda = "Vrsta 18",
                            VrstaPovrsineId = 1
                        },
                        new
                        {
                            Id = 19,
                            Naziv = "Povrsina 19",
                            Oznaka = 111,
                            ProjekatZaGradjevinskuDozvoluId = 1,
                            Status = 0,
                            VrstaPoda = "Vrsta 19",
                            VrstaPovrsineId = 2
                        },
                        new
                        {
                            Id = 20,
                            Naziv = "Povrsina 20",
                            Oznaka = 978,
                            ProjekatZaGradjevinskuDozvoluId = 1,
                            Status = 0,
                            VrstaPoda = "Vrsta 20",
                            VrstaPovrsineId = 3
                        },
                        new
                        {
                            Id = 21,
                            Naziv = "Povrsina 21",
                            Oznaka = 65,
                            ProjekatZaGradjevinskuDozvoluId = 6,
                            Status = 0,
                            VrstaPoda = "Vrsta 21",
                            VrstaPovrsineId = 4
                        },
                        new
                        {
                            Id = 22,
                            Naziv = "Povrsina 22",
                            Oznaka = 234,
                            ProjekatZaGradjevinskuDozvoluId = 9,
                            Status = 0,
                            VrstaPoda = "Vrsta 22",
                            VrstaPovrsineId = 2
                        },
                        new
                        {
                            Id = 23,
                            Naziv = "Povrsina 23",
                            Oznaka = 543,
                            ProjekatZaGradjevinskuDozvoluId = 8,
                            Status = 0,
                            VrstaPoda = "Vrsta 23",
                            VrstaPovrsineId = 3
                        },
                        new
                        {
                            Id = 24,
                            Naziv = "Povrsina 24",
                            Oznaka = 54,
                            ProjekatZaGradjevinskuDozvoluId = 10,
                            Status = 0,
                            VrstaPoda = "Vrsta 24",
                            VrstaPovrsineId = 1
                        },
                        new
                        {
                            Id = 25,
                            Naziv = "Povrsina 25",
                            Oznaka = 7865,
                            ProjekatZaGradjevinskuDozvoluId = 8,
                            Status = 0,
                            VrstaPoda = "Vrsta 25",
                            VrstaPovrsineId = 5
                        },
                        new
                        {
                            Id = 26,
                            Naziv = "Povrsina 26",
                            Oznaka = 465,
                            ProjekatZaGradjevinskuDozvoluId = 8,
                            Status = 0,
                            VrstaPoda = "Vrsta 26",
                            VrstaPovrsineId = 5
                        },
                        new
                        {
                            Id = 27,
                            Naziv = "Povrsina 27",
                            Oznaka = 123,
                            ProjekatZaGradjevinskuDozvoluId = 7,
                            Status = 0,
                            VrstaPoda = "Vrsta 27",
                            VrstaPovrsineId = 1
                        },
                        new
                        {
                            Id = 28,
                            Naziv = "Povrsina 28",
                            Oznaka = 541,
                            ProjekatZaGradjevinskuDozvoluId = 7,
                            Status = 0,
                            VrstaPoda = "Vrsta 28",
                            VrstaPovrsineId = 1
                        },
                        new
                        {
                            Id = 29,
                            Naziv = "Povrsina 29",
                            Oznaka = 313,
                            ProjekatZaGradjevinskuDozvoluId = 6,
                            Status = 0,
                            VrstaPoda = "Vrsta 29",
                            VrstaPovrsineId = 2
                        },
                        new
                        {
                            Id = 30,
                            Naziv = "Povrsina 30",
                            Oznaka = 467,
                            ProjekatZaGradjevinskuDozvoluId = 6,
                            Status = 0,
                            VrstaPoda = "Vrsta 30",
                            VrstaPovrsineId = 3
                        },
                        new
                        {
                            Id = 31,
                            Naziv = "Povrsina 41",
                            Oznaka = 984,
                            ProjekatZaGradjevinskuDozvoluId = 6,
                            Status = 0,
                            VrstaPoda = "Vrsta 31",
                            VrstaPovrsineId = 4
                        },
                        new
                        {
                            Id = 32,
                            Naziv = "Povrsina 42",
                            Oznaka = 32,
                            ProjekatZaGradjevinskuDozvoluId = 9,
                            Status = 0,
                            VrstaPoda = "Vrsta 32",
                            VrstaPovrsineId = 2
                        },
                        new
                        {
                            Id = 33,
                            Naziv = "Povrsina 43",
                            Oznaka = 7764,
                            ProjekatZaGradjevinskuDozvoluId = 8,
                            Status = 0,
                            VrstaPoda = "Vrsta 33",
                            VrstaPovrsineId = 3
                        },
                        new
                        {
                            Id = 34,
                            Naziv = "Povrsina 44",
                            Oznaka = 65342,
                            ProjekatZaGradjevinskuDozvoluId = 10,
                            Status = 0,
                            VrstaPoda = "Vrsta 34",
                            VrstaPovrsineId = 1
                        },
                        new
                        {
                            Id = 35,
                            Naziv = "Povrsina 45",
                            Oznaka = 3219,
                            ProjekatZaGradjevinskuDozvoluId = 8,
                            Status = 0,
                            VrstaPoda = "Vrsta 35",
                            VrstaPovrsineId = 5
                        },
                        new
                        {
                            Id = 36,
                            Naziv = "Povrsina 46",
                            Oznaka = 890,
                            ProjekatZaGradjevinskuDozvoluId = 8,
                            Status = 0,
                            VrstaPoda = "Vrsta 36",
                            VrstaPovrsineId = 5
                        },
                        new
                        {
                            Id = 37,
                            Naziv = "Povrsina 47",
                            Oznaka = 203,
                            ProjekatZaGradjevinskuDozvoluId = 7,
                            Status = 0,
                            VrstaPoda = "Vrsta 37",
                            VrstaPovrsineId = 1
                        },
                        new
                        {
                            Id = 38,
                            Naziv = "Povrsina 48",
                            Oznaka = 110,
                            ProjekatZaGradjevinskuDozvoluId = 7,
                            Status = 0,
                            VrstaPoda = "Vrsta 38",
                            VrstaPovrsineId = 1
                        },
                        new
                        {
                            Id = 39,
                            Naziv = "Povrsina 49",
                            Oznaka = 903,
                            ProjekatZaGradjevinskuDozvoluId = 6,
                            Status = 0,
                            VrstaPoda = "Vrsta 39",
                            VrstaPovrsineId = 2
                        },
                        new
                        {
                            Id = 40,
                            Naziv = "Povrsina 50",
                            Oznaka = 314,
                            ProjekatZaGradjevinskuDozvoluId = 6,
                            Status = 0,
                            VrstaPoda = "Vrsta 40",
                            VrstaPovrsineId = 3
                        });
                });

            modelBuilder.Entity("Ideastudio.Domain.ProjekatZaGradjevinskuDozvolu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumIzrade")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdejnoResenjeId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NazivIdejnogResenja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusDokumenta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdejnoResenjeId");

                    b.ToTable("ProjekatZaGradjevinskuDozvolu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DatumIzrade = new DateTime(2020, 6, 18, 16, 40, 24, 747, DateTimeKind.Utc).AddTicks(9438),
                            IdejnoResenjeId = 2,
                            Naziv = "Projekat 1",
                            StatusDokumenta = 0
                        },
                        new
                        {
                            Id = 2,
                            DatumIzrade = new DateTime(2020, 6, 18, 16, 40, 24, 748, DateTimeKind.Utc).AddTicks(866),
                            IdejnoResenjeId = 7,
                            Naziv = "Projekat 2",
                            StatusDokumenta = 0
                        },
                        new
                        {
                            Id = 3,
                            DatumIzrade = new DateTime(2020, 6, 18, 16, 40, 24, 748, DateTimeKind.Utc).AddTicks(892),
                            IdejnoResenjeId = 9,
                            Naziv = "Projekat 3",
                            StatusDokumenta = 0
                        },
                        new
                        {
                            Id = 4,
                            DatumIzrade = new DateTime(2020, 6, 18, 16, 40, 24, 748, DateTimeKind.Utc).AddTicks(895),
                            IdejnoResenjeId = 1,
                            Naziv = "Projekat 4",
                            StatusDokumenta = 0
                        },
                        new
                        {
                            Id = 5,
                            DatumIzrade = new DateTime(2020, 6, 18, 16, 40, 24, 748, DateTimeKind.Utc).AddTicks(897),
                            IdejnoResenjeId = 5,
                            Naziv = "Projekat 5",
                            StatusDokumenta = 0
                        },
                        new
                        {
                            Id = 6,
                            DatumIzrade = new DateTime(2020, 6, 18, 16, 40, 24, 748, DateTimeKind.Utc).AddTicks(898),
                            IdejnoResenjeId = 3,
                            Naziv = "Projekat 6",
                            StatusDokumenta = 0
                        },
                        new
                        {
                            Id = 7,
                            DatumIzrade = new DateTime(2020, 6, 18, 16, 40, 24, 748, DateTimeKind.Utc).AddTicks(900),
                            IdejnoResenjeId = 10,
                            Naziv = "Projekat 7",
                            StatusDokumenta = 0
                        },
                        new
                        {
                            Id = 8,
                            DatumIzrade = new DateTime(2020, 6, 18, 16, 40, 24, 748, DateTimeKind.Utc).AddTicks(902),
                            IdejnoResenjeId = 4,
                            Naziv = "Projekat 8",
                            StatusDokumenta = 0
                        },
                        new
                        {
                            Id = 9,
                            DatumIzrade = new DateTime(2020, 6, 18, 16, 40, 24, 748, DateTimeKind.Utc).AddTicks(904),
                            IdejnoResenjeId = 8,
                            Naziv = "Projekat 9",
                            StatusDokumenta = 0
                        },
                        new
                        {
                            Id = 10,
                            DatumIzrade = new DateTime(2020, 6, 18, 16, 40, 24, 748, DateTimeKind.Utc).AddTicks(906),
                            IdejnoResenjeId = 6,
                            Naziv = "Projekat 10",
                            StatusDokumenta = 0
                        });
                });

            modelBuilder.Entity("Ideastudio.Domain.Prostorija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("VrstaPovrsineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VrstaPovrsineId");

                    b.ToTable("Prostorija");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Prostorija 1",
                            VrstaPovrsineId = 1
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "Prostorija 2",
                            VrstaPovrsineId = 5
                        },
                        new
                        {
                            Id = 3,
                            Naziv = "Prostorija 3",
                            VrstaPovrsineId = 3
                        },
                        new
                        {
                            Id = 4,
                            Naziv = "Prostorija 4",
                            VrstaPovrsineId = 2
                        },
                        new
                        {
                            Id = 5,
                            Naziv = "Prostorija 5",
                            VrstaPovrsineId = 4
                        });
                });

            modelBuilder.Entity("Ideastudio.Domain.VrstaPovrsine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("VrstaPovrsine");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Vrsta povrsine 1"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "Vrsta povrsine 2"
                        },
                        new
                        {
                            Id = 3,
                            Naziv = "Vrsta povrsine 3"
                        },
                        new
                        {
                            Id = 4,
                            Naziv = "Vrsta povrsine 4"
                        },
                        new
                        {
                            Id = 5,
                            Naziv = "Vrsta povrsine 5"
                        });
                });

            modelBuilder.Entity("Ideastudio.Domain.IdejnoResenje", b =>
                {
                    b.HasOne("Ideastudio.Domain.GlavniProjektant", "GlavniProjektant")
                        .WithMany("IdejnaResenja")
                        .HasForeignKey("GlavniProjektantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ideastudio.Domain.LokacijskaDozvola", "LokacijskaDozvola")
                        .WithMany("IdejnaResenja")
                        .HasForeignKey("LokacijskaDozvolaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ideastudio.Domain.Objekat", "Objekat")
                        .WithMany("IdejnaResenja")
                        .HasForeignKey("ObjekatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ideastudio.Domain.LokacijskaDozvola", b =>
                {
                    b.HasOne("Ideastudio.Domain.InformacijeOLokaciji", "InformacijeOLokaciji")
                        .WithMany("LokacijskeDozvole")
                        .HasForeignKey("InformacijeOLokacijiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ideastudio.Domain.Povrsina", b =>
                {
                    b.HasOne("Ideastudio.Domain.ProjekatZaGradjevinskuDozvolu", "ProjekatZaGradjevinskuDozvolu")
                        .WithMany("Povrsine")
                        .HasForeignKey("ProjekatZaGradjevinskuDozvoluId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ideastudio.Domain.VrstaPovrsine", "VrstaPovrsine")
                        .WithMany("Povrsine")
                        .HasForeignKey("VrstaPovrsineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ideastudio.Domain.ProjekatZaGradjevinskuDozvolu", b =>
                {
                    b.HasOne("Ideastudio.Domain.IdejnoResenje", "IdejnoResenje")
                        .WithMany("ProjektiZaGradjevinskuDozvolu")
                        .HasForeignKey("IdejnoResenjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ideastudio.Domain.Prostorija", b =>
                {
                    b.HasOne("Ideastudio.Domain.VrstaPovrsine", "VrstaPovrsine")
                        .WithMany("Prostorije")
                        .HasForeignKey("VrstaPovrsineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
